### PR TITLE
Add footer component

### PR DESCRIPTION
**Pull request by Ishaan-11**
Added footer component as per the issue [Create a footer component](https://github.com/AltCtrlDel1999/OS-Mate/issues/4)

image

### CODE REVIEW

**Review by AltCtrlDel1999 — CHANGES_REQUESTED** [review]
Hey, @Ishaan-11 Thank you for contributing to OS-Mate.
Please add
Project Title 
About line from the readme 
and GitHub link to this project in footer
Try to make It look good.

**Comment by Ishaan-11** [comment]
@AltCtrlDel1999 any changes for this?
image

**Comment by AltCtrlDel1999** [comment]
@Ishaan-11  Yupp That seems good

**Comment by Ishaan-11** [comment]
@AltCtrlDel1999  i have pushed the changes but this PR is not updated.
See the changes are visible in [forked repo](https://github.com/Ishaan-11/OS-Mate/commit/0e6c551f8ae80a68bb69481d93c29e9c98bc74f3).
But why it is not showing here.

**Comment by AltCtrlDel1999** [comment]
@Ishaan-11 Try making another dummy commit on the develop branch if the problem still persists reopen the pull request

**Review by AltCtrlDel1999 — APPROVED** [review]

**Pull request merged**
